name: Build and Release App

on:
  push:
    tags:
      - 'v*'  # Только при пуше тега, например v1.0

  workflow_dispatch:


permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check that logo.ico is there
        run: dir assets

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe with PyInstaller
        run: pyinstaller main.py --noconfirm --onefile --icon=assets/logo.ico --add-data "assets/logo.ico;assets" --add-data "assets/logo.png;assets" --name=dev-tool-hoi4

      - name: Prepare zip
        run: |
          mkdir dist_upload
          copy dist\dev-tool-hoi4.exe dist_upload\
          powershell Compress-Archive -Path dist_upload\* -DestinationPath dev-tool-hoi4.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dev-tool-hoi4.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
